# _config.yml
title: Deep Learning Portfolio
author: Jezzel Faith Gier
logo: logo.png

execute:
  execute_notebooks: "off"   # or "auto" if you want JB to run them

html:
  favicon: logo.png
  home_page_in_navbar: true
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  baseurl: "https://jzelfthr.github.io/DEEP_LEARNING/"
  extra_navbar: ""
  extra_footer: "Built with Jupyter Book"

repository:
  url: "https://github.com/Jzelfthr/DEEP_LEARNING"
  branch: main
  path_to_book: "."
